//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by d2-i18n-generate.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import i18n from '@dhis2/d2-i18n'

import enTranslations from './en/translations.json'
import frTranslations from './fr/translations.json'
import ptTranslations from './pt/translations.json'

const namespace = 'default'
i18n.addResources('en', namespace, enTranslations)
i18n.addResources('fr', namespace, frTranslations)
i18n.addResources('pt', namespace, ptTranslations)

export default i18n
